#! /bin/zsh
#
# vi-mode colour changing
#   http://www.zsh.org/mla/users/2006/msg01196.html

setopt prompt_subst
autoload colors
colors

rst="%{%b%s%u$reset_color%}"
bgc="%{%(?.$rst.%S)%}"


function lprompt {
    local col1 col2 ch1 ch2
    col1="%{%b$fg[$2]%}"
    col2="%{$4$fg[$3]%}"
    ch1=$col1${1[1]}
    ch2=$col1${1[2]}

    local git_b git_s col_b col_s
    col_b="%{$fg[green]%}"
    col_s="%{$fg[red]%}"
    
    PROMPT="\
$bgc$ch1\
%{$fg_bold[white]%}%m:\
$bgc$col2%B%1~%b\
$ch2$rst \
$col2%#$rst "
}

function _get_git_rprompt {
    local git_branch
    local returned
    local color

    returned=""
    
    git_branch="$(parse_git_branch)"
    if [ -n "$git_branch" ]; then
        returned="$returned:$git_branch"
    fi
    
    echo -n "$returned"
}

function _rprompt_dir {
    local short
    short="%{$fg[green]%}${PWD/$HOME/~}%{%b%s%u$reset_color%}"
    echo -n "$short$(_get_git_rprompt)"
}

function rprompt {
    local col1 col2 ch1 ch2
    col1="%{$fg[$2]%}"
    col2="%{$4$fg[$3]%}"
    ch1=$col1${1[1]}
    ch2=$col1${1[2]}

    local _dir='$(_rprompt_dir)'

    RPROMPT="\
$rst$ch1\
$col2%*:%n\
$col1:\
$col2%B$_dir%b\
$ch2$rst"
}

if [ $UID -eq 0 ]; then
    PROMPT="$bgc%{%B$fg[yellow]%}[%{$fg[red]%}%n %m%{$fg[yellow]%}]$rst "
    RPROMPT="$rst%{$fg[red]%}(%B%{$fg[red]%}%~%b%{$fg[red]%})$rst "
else
    case $HOST in
        *)
            lprompt '{}' green green
            rprompt '()' yellow white
            ;;
    esac
fi

unset rst bgc

case $TERM in
	xterm*)
  		# this updates title bar before prompt is printed
		  precmd () {
		    echo  -n \\033\]2\;$USER@$HOST:$_\\07;
		  }

		  # this updates title bar while command is running
		  xterm-accept-line () { print -nr -- "]2;$BUFFER"; zle .accept-line; }
		  zle -N accept-line xterm-accept-line
	;;

	*)
	;;
esac

# ------------------------
#       PS1=$'%{\e[34;1m%}%20>..>%1~%>>>%{\e[0m%}'
#
#       function zle-keymap-select {
#               PS1=${${1/vicmd/$'%{\e[31;1m%}'}/(viins|main)/$'%{\e[34;1m%}'}${PS1#*%\}}
#               zle reset-prompt
#       }


# ------------------------
#       function zle-line-init zle-keymap-select {
#               RPS1="${${KEYMAP/vicmd/-- NORMAL --}/(main|viins)/-- INSERT --}"
#               RPS2=$RPS1
#               RPS3=$RPS1
#               RPS4=$RPS1
#               zle reset-prompt
#       }
#       zle -N zle-line-init
