#!sh

function newline() { printf "$@\n"; }
function color() {
  output="\e[$1m"
  shift
  [ -n "$1" ] && output="$output$@\e[00m"
  printf "$output"
}
function reset() { color "00"; }
function red() { color "01;31" "$@"; }
function yellow() { color "01;33" "$@"; }
function blue() { color "01;34" "$@"; }
function white() { color "01;37" "$@" ; }
function green() { color "01;32" "$@" ; }

function error() { newline "$(red "$@")"; }
function warning() { newline "$(yellow "$@")"; }
function notification() { newline "$(white "$@")"; }
