#!/bin/zsh

VIRTUAL_ENV_DISABLE_PROMPT=True

function virtualenv_name() {
    local virtualenv="$1"
    if echo "$virtualenv" | grep .venv > /dev/null; then
        basename $(dirname "$virtualenv")
    else
        basename "$virtualenv"
    fi
}

function active_virtualenv() {
    if [ -z "$VIRTUAL_ENV" ]; then
        # not in a virtualenv
        return
    fi

    virtualenv_name "$VIRTUAL_ENV"
}

function enclosing_virtualenv() {
    if ! which walkup > /dev/null; then
        return
    fi
    local virtualenv="$(walkup bin/activate .venv/bin/activate | cut -f1 -d:)"
    if [ -z "$virtualenv" ]; then
        # not in a virtualenv
        return
    fi

    virtualenv_name "$virtualenv"
}

function act() {
    if [ -n "$1" ]; then
        if [ ! -d "$1" ]; then
            echo "act: $1 no such directory"
            return 1
        fi
        if [ ! -e "$1/bin/activate" ]; then
            echo "act: $1 is not a virtualenv"
            return 1
        fi

        if which deactivate > /dev/null; then
            deactivate
        fi
        cd "$1"
        source bin/activate
    else
        local virtualenv="$(walkup bin/activate .venv/bin/activate | tr : /)"
        if [ -z "$virtualenv" ]; then
            echo "act: not in a virtualenv"
            return 1
        fi
        source "$virtualenv"
    fi
}

function cdv() {
    local virtualenv="$VIRTUAL_ENV"
    if [ -z "$virtualenv" ]; then
        echo "cdv: not in a virtualenv"
        return 1
    fi
    if echo $virtualenv | grep .venv > /dev/null; then
        local virtualenv=$(dirname "$virtualenv")
    fi
    
    cd "$virtualenv"/"$1"
}
